
services:

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: panaderia
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

    networks:
      - panaderia-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  eureka-service:
    image: eureka-server-image
    build: ./eureka-server
    ports:
      - "8761:8761"
    networks:
      - panaderia-net
    depends_on:
      mysql:
        condition: service_healthy

  inventario-service:
    image: inventario-service-image
    build: ./inventario-service
    ports:
      - "8081:8081"
    depends_on:
      eureka-service:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/panaderia
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    networks:
      - panaderia-net

  compras-service:
    image: compras-service-image
    build: ./compras-service
    ports:
      - "8082:8082"
    depends_on:
      eureka-service:
        condition: service_started
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/panaderia
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - panaderia-net

  api-gateway:
    image: api-gateway-image
    build: ./gateway-service
    ports:
      - "8083:8083"
    depends_on:
      inventario-service:
        condition: service_started
      compras-service:
        condition: service_started
      eureka-service:
        condition: service_started
    networks:
      - panaderia-net

  frontend:
    image: frontend-image
    build: ./Cliente
    ports:
      - "8084:8084"
    depends_on:
      api-gateway:
        condition: service_started
    networks:
      - panaderia-net

volumes:
  mysql_data:

networks:
  panaderia-net:
    name: panaderia-net
    driver: bridge
