services:
  # Contenedor de la aplicaci칩n Spring Boot
  panaderia-backend:
    build:
      context: .
      dockerfile: Dockerfile  # Utiliza el Dockerfile para Spring Boot
    ports:
      - "8081:8081"  # Exponemos el puerto 8081 para la aplicaci칩n web
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://panaderia-mysql.mysql.database.azure.com:3306/panaderia  # URL de conexi칩n a Azure Database for MySQL
      - SPRING_DATASOURCE_USERNAME=admin123  # Usa el usuario de la base de datos que configuraste en Azure
      - SPRING_DATASOURCE_PASSWORD=8qPdQA7VZiPL2iF  # La contrase침a del usuario
    networks:
      - panaderia-net

# Definir la red panaderia-net
networks:
  panaderia-net:
    driver: bridge
